name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # Change this to master if your default branch is master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use the Node version matching your local environment
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci # Using 'npm ci' is preferred in CI/CD for clean, faster installs

      - name: Build Application
        run: npm run build -- --base-href /devdigvijay-portfolio/

      - name: Copy index.html to 404.html (For Angular Routing)
        run: cp dist/dev-digvijay/browser/ dist/devdigvijay-portfolio/browser/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/<PROJECT_NAME>/browser # Path to your compiled static files
          branch: gh-pages # The branch the action will deploy to